import random


DIRECTIONS = ["left", "right", "up", "down"]


def transpose(board):
    """
    Transforms rows into columns.

    Example:

    1 2 3
    4 5 6
    7 8 9

    becomes:

    1 4 7
    2 5 8
    3 6 9
    """

    return [
        [board[j][i] for j in range(len(board))]
        for i in range(len(board[0]))
    ]


def move_row_left(row):
    """
    Moves a single row to the left.

    Also performs merges and calculates the score
    generated by this row.

    Returns:

        new_row, score
    """

    # Remove zeros
    numbers = [x for x in row if x != 0]

    result = []
    score = 0

    i = 0

    while i < len(numbers):

        # Two equal numbers can be combined
        if (
            i + 1 < len(numbers)
            and numbers[i] == numbers[i + 1]
        ):
            merged = numbers[i] * 2

            result.append(merged)

            # The score received is the value of the created tile
            score += merged

            i += 2

        else:
            result.append(numbers[i])
            i += 1

    # Complete the row with zeros
    result += [0] * (4 - len(result))

    return result, score


def move_row_right(row):
    """
    Performs the right movement reusing
    the left movement logic.
    """

    reversed_row = row[::-1]

    new_row, score = move_row_left(reversed_row)

    return new_row[::-1], score


def move_rows(board, move_function):
    """
    Applies a movement function to all rows.

    Also sums the score of all rows.
    """

    new_board = []
    score = 0

    for row in board:
        new_row, row_score = move_function(row)

        new_board.append(new_row)

        score += row_score

    return new_board, score


def move(board, direction):
    """
    Executes a movement.

    Returns:

        new_board
        reward
        moved

    reward = score gained in this movement.

    moved = indicates if the board actually changed.
    """

    original_board = [row[:] for row in board]

    if direction == "left":

        new_board, score = move_rows(
            board,
            move_row_left
        )

    elif direction == "right":

        new_board, score = move_rows(
            board,
            move_row_right
        )

    elif direction == "up":

        transposed = transpose(board)

        transposed, score = move_rows(
            transposed,
            move_row_left
        )

        new_board = transpose(transposed)

    elif direction == "down":

        transposed = transpose(board)

        transposed, score = move_rows(
            transposed,
            move_row_right
        )

        new_board = transpose(transposed)

    else:
        raise ValueError(
            f"Invalid direction: {direction}"
        )

    moved = new_board != original_board

    return new_board, score, moved


def available_moves(board):
    """
    Returns the moves that would actually
    change the board.
    """

    moves = []

    for direction in DIRECTIONS:

        _, _, moved = move(board, direction)

        if moved:
            moves.append(direction)

    return moves


def is_game_over(board):
    """
    The game is over when no moves are possible.
    """

    return len(available_moves(board)) == 0


def add_new_tile(board):
    """
    Adds a new tile:

    90% -> 2
    10% -> 4

    Creates a copy of the board to not modify the original.
    """

    board = [row[:] for row in board]

    empty_cells = []

    for i in range(4):
        for j in range(4):

            if board[i][j] == 0:
                empty_cells.append((i, j))

    if empty_cells:

        row, col = random.choice(empty_cells)

        board[row][col] = (
            2 if random.random() < 0.9 else 4
        )

    return board


def reset_game():
    """
    Creates a new board with two initial tiles.
    """

    board = [
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
    ]

    board = add_new_tile(board)
    board = add_new_tile(board)

    return board